email.from=jobseeker.noreply@gmail.com
email.username=jobseeker.noreply@gmail.com
email.password=vwoh anhs mfcb cnxv
email.host=smtp.gmail.com
email.port=587
email.auth=true
email.starttls=true
email.debug=false